PRAGMA foreign_keys=ON;
CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY,email TEXT UNIQUE NOT NULL,name TEXT NOT NULL,password_hash TEXT NOT NULL,role TEXT NOT NULL DEFAULT 'buyer',verified INTEGER NOT NULL DEFAULT 0,balance INTEGER NOT NULL DEFAULT 0,avatar_url TEXT DEFAULT '',avatar_source TEXT NOT NULL DEFAULT 'default',vip INTEGER NOT NULL DEFAULT 0,blue_verified INTEGER NOT NULL DEFAULT 0,seller_trial_until INTEGER,seller_paid_until INTEGER,created_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS sessions(token TEXT PRIMARY KEY,user_id TEXT NOT NULL,expires_at INTEGER NOT NULL,created_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS games(id TEXT PRIMARY KEY,name TEXT UNIQUE NOT NULL,active INTEGER NOT NULL DEFAULT 1,created_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS products(id TEXT PRIMARY KEY,seller_id TEXT NOT NULL,title TEXT NOT NULL,game TEXT NOT NULL,description TEXT DEFAULT '',price INTEGER NOT NULL,login_type TEXT NOT NULL DEFAULT 'gmail',active INTEGER NOT NULL DEFAULT 1,created_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS product_images(id TEXT PRIMARY KEY,product_id TEXT NOT NULL,url TEXT NOT NULL,sort_order INTEGER NOT NULL DEFAULT 0,created_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS transactions(id TEXT PRIMARY KEY,buyer_id TEXT NOT NULL,seller_id TEXT NOT NULL,product_id TEXT NOT NULL,title TEXT NOT NULL,price INTEGER NOT NULL,fee INTEGER NOT NULL,total INTEGER NOT NULL,status TEXT NOT NULL DEFAULT 'waiting_payment',created_at INTEGER NOT NULL,paid_at INTEGER,completed_at INTEGER);
CREATE TABLE IF NOT EXISTS transaction_groups(id TEXT PRIMARY KEY,transaction_id TEXT UNIQUE NOT NULL,name TEXT NOT NULL,created_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS group_members(group_id TEXT NOT NULL,user_id TEXT NOT NULL,role TEXT NOT NULL,PRIMARY KEY(group_id,user_id));
CREATE TABLE IF NOT EXISTS messages(id TEXT PRIMARY KEY,room_id TEXT NOT NULL,uid TEXT NOT NULL,name TEXT NOT NULL,role TEXT NOT NULL,text TEXT NOT NULL,created_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS chats(id TEXT PRIMARY KEY,kind TEXT NOT NULL DEFAULT 'direct',user_a TEXT NOT NULL,user_b TEXT NOT NULL,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL,UNIQUE(user_a,user_b));
CREATE TABLE IF NOT EXISTS chat_messages(id TEXT PRIMARY KEY,chat_id TEXT NOT NULL,sender_id TEXT NOT NULL,text TEXT NOT NULL,created_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS payments(id TEXT PRIMARY KEY,transaction_id TEXT UNIQUE NOT NULL,method TEXT NOT NULL,amount INTEGER NOT NULL,reference TEXT DEFAULT '',proof_url TEXT DEFAULT '',status TEXT NOT NULL DEFAULT 'pending',created_at INTEGER NOT NULL,verified_at INTEGER);
CREATE TABLE IF NOT EXISTS payment_methods(id TEXT PRIMARY KEY,code TEXT UNIQUE NOT NULL,name TEXT NOT NULL,kind TEXT NOT NULL,account_name TEXT DEFAULT '',account_number TEXT DEFAULT '',qr_url TEXT DEFAULT '',instructions TEXT DEFAULT '',active INTEGER NOT NULL DEFAULT 1,sort_order INTEGER NOT NULL DEFAULT 0,updated_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS notifications(id TEXT PRIMARY KEY,user_id TEXT NOT NULL,title TEXT NOT NULL,body TEXT NOT NULL,type TEXT NOT NULL,ref_id TEXT DEFAULT '',read_at INTEGER,created_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS push_tokens(id TEXT PRIMARY KEY,user_id TEXT NOT NULL,token TEXT UNIQUE NOT NULL,platform TEXT NOT NULL DEFAULT 'android',active INTEGER NOT NULL DEFAULT 1,updated_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS deliveries(transaction_id TEXT PRIMARY KEY,email TEXT NOT NULL,password_cipher TEXT NOT NULL,created_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS withdrawals(id TEXT PRIMARY KEY,seller_id TEXT NOT NULL,amount INTEGER NOT NULL,method TEXT NOT NULL,destination TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'requested',created_at INTEGER NOT NULL,processed_at INTEGER);
CREATE TABLE IF NOT EXISTS seller_plans(id TEXT PRIMARY KEY,name TEXT NOT NULL,price INTEGER NOT NULL,duration_days INTEGER NOT NULL,active INTEGER NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS seller_subscriptions(id TEXT PRIMARY KEY,seller_id TEXT NOT NULL,plan_id TEXT NOT NULL,starts_at INTEGER NOT NULL,expires_at INTEGER NOT NULL,status TEXT NOT NULL DEFAULT 'active');
CREATE TABLE IF NOT EXISTS app_settings(key TEXT PRIMARY KEY,value TEXT NOT NULL,updated_at INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS idx_products_active ON products(active);
CREATE INDEX IF NOT EXISTS idx_tx_buyer ON transactions(buyer_id,created_at);
CREATE INDEX IF NOT EXISTS idx_tx_seller ON transactions(seller_id,created_at);
CREATE INDEX IF NOT EXISTS idx_group_members_user ON group_members(user_id);
CREATE INDEX IF NOT EXISTS idx_messages_room ON messages(room_id,created_at);
CREATE INDEX IF NOT EXISTS idx_notifications_user ON notifications(user_id,created_at);
CREATE INDEX IF NOT EXISTS idx_push_tokens_user ON push_tokens(user_id,active);
CREATE INDEX IF NOT EXISTS idx_chat_messages ON chat_messages(chat_id,created_at);
