

const H={"content-type":"application/json","access-control-allow-origin":"*","access-control-allow-headers":"content-type,authorization,x-admin-secret","access-control-allow-methods":"GET,POST,PUT,DELETE,OPTIONS"};
const json=(x,s=200)=>new Response(JSON.stringify(x),{status:s,headers:H});
const now=()=>Date.now(), id=()=>crypto.randomUUID(), enc=new TextEncoder();
const body=r=>r.json().catch(()=>({}));
async function sha(s){const b=await crypto.subtle.digest("SHA-256",enc.encode(s));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,"0")).join("")}
function b64u(a){let s=typeof a==="string"?a:String.fromCharCode(...a);return btoa(s).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/,"")}
function pemToBuf(p){const x=p.replace(/-----BEGIN PRIVATE KEY-----|-----END PRIVATE KEY-----|\s/g,"");const bin=atob(x);return Uint8Array.from(bin,c=>c.charCodeAt(0))}
async function fcmToken(env){
  if(!env.FCM_SERVICE_ACCOUNT_JSON)return null;
  const sa=typeof env.FCM_SERVICE_ACCOUNT_JSON==="string"?JSON.parse(env.FCM_SERVICE_ACCOUNT_JSON):env.FCM_SERVICE_ACCOUNT_JSON;
  const iat=Math.floor(Date.now()/1000),head=b64u(JSON.stringify({alg:"RS256",typ:"JWT"})),claim=b64u(JSON.stringify({iss:sa.client_email,scope:"https://www.googleapis.com/auth/firebase.messaging",aud:"https://oauth2.googleapis.com/token",iat,exp:iat+3600}));
  const key=await crypto.subtle.importKey("pkcs8",pemToBuf(sa.private_key),{name:"RSASSA-PKCS1-v1_5",hash:"SHA-256"},false,["sign"]);
  const sig=await crypto.subtle.sign("RSASSA-PKCS1-v1_5",key,enc.encode(head+"."+claim));
  const jwt=head+"."+claim+"."+b64u(sig);
  const tr=await fetch("https://oauth2.googleapis.com/token",{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded"},body:"grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Ajwt-bearer&assertion="+encodeURIComponent(jwt)});
  if(!tr.ok)return null; return (await tr.json()).access_token;
}
async function push(env,userId,title,text,data={}){
  try{
    const rows=await env.DB.prepare("SELECT token FROM push_tokens WHERE user_id=? AND active=1").bind(userId).all();
    if(!rows.results.length)return;
    const access=await fcmToken(env); if(!access)return;
    const sa=JSON.parse(env.FCM_SERVICE_ACCOUNT_JSON), url=`https://fcm.googleapis.com/v1/projects/${sa.project_id}/messages:send`;
    for(const r of rows.results){
      const res=await fetch(url,{method:"POST",headers:{"authorization":"Bearer "+access,"content-type":"application/json"},body:JSON.stringify({message:{token:r.token,data:Object.fromEntries(Object.entries({title,body:text,...data}).map(([k,v])=>[k,String(v??"")])),android:{priority:"HIGH"}}})});
      if(res.status===404||res.status===400){await env.DB.prepare("UPDATE push_tokens SET active=0 WHERE token=?").bind(r.token).run()}
    }
  }catch(_){}
}
async function notify(env,userId,title,text,type,refId="",data={}){
  await env.DB.prepare("INSERT INTO notifications(id,user_id,title,body,type,ref_id,created_at) VALUES(?,?,?,?,?,?,?)").bind(id(),userId,title,text,type,refId,now()).run();
  await push(env,userId,title,text,{type,refId,...data});
}
async function auth(r,env){
 const h=r.headers.get("authorization")||"",t=h.startsWith("Bearer ")?h.slice(7):"";
 if(!t)return null;
 return env.DB.prepare("SELECT u.* FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token=? AND s.expires_at>?").bind(t,now()).first();
}
const fee=p=>p<100000?1000:p<1000000?2500:5000;
const prof=u=>({id:u.id,email:u.email,name:u.name,role:u.role,verified:!!u.verified,balance:u.balance||0,avatarUrl:u.avatar_url||"",avatarSource:u.avatar_source||"default",vip:!!u.vip,blueVerified:!!u.blue_verified,sellerActive:u.role==="seller"&&Math.max(u.seller_trial_until||0,u.seller_paid_until||0)>now()});
async function admin(env){return env.DB.prepare("SELECT * FROM users WHERE role='admin' ORDER BY created_at LIMIT 1").first()}
async function group(env,t){
 let g=await env.DB.prepare("SELECT * FROM transaction_groups WHERE transaction_id=?").bind(t.id).first();
 if(g)return g;
 const n=await env.DB.prepare("SELECT COUNT(*) n FROM transaction_groups").first(),num=Number(n.n||0)+1;
 const gid=id(); await env.DB.prepare("INSERT INTO transaction_groups(id,transaction_id,name,created_at) VALUES(?,?,?,?)").bind(gid,t.id,`Velora ${num}`,now()).run();
 const a=await admin(env); for(const [u,r] of [[t.buyer_id,"buyer"],[t.seller_id,"seller"],[a?.id,"admin"]]) if(u)await env.DB.prepare("INSERT OR IGNORE INTO group_members(group_id,user_id,role) VALUES(?,?,?)").bind(gid,u,r).run();
 return env.DB.prepare("SELECT * FROM transaction_groups WHERE id=?").bind(gid).first();
}
async function encDelivery(text,secret){
 const raw=await crypto.subtle.digest("SHA-256",enc.encode(secret||"CHANGE_ME")); const key=await crypto.subtle.importKey("raw",raw,{name:"AES-GCM"},false,["encrypt"]);
 const iv=crypto.getRandomValues(new Uint8Array(12)),c=await crypto.subtle.encrypt({name:"AES-GCM",iv},key,enc.encode(text));return b64u(new Uint8Array([...iv,...new Uint8Array(c)]))
}
async function decDelivery(v,secret){
 const raw=await crypto.subtle.digest("SHA-256",enc.encode(secret||"CHANGE_ME")); const key=await crypto.subtle.importKey("raw",raw,{name:"AES-GCM"},false,["decrypt"]);
 const pad=v.replace(/-/g,"+").replace(/_/g,"/")+"===".slice((v.length+3)%4),bin=atob(pad),a=Uint8Array.from(bin,c=>c.charCodeAt(0));const p=await crypto.subtle.decrypt({name:"AES-GCM",iv:a.slice(0,12)},key,a.slice(12));return new TextDecoder().decode(p)
}
async function sendGroup(env,t,sender,text){
 const g=await group(env,t); await env.DB.prepare("INSERT INTO messages(id,room_id,uid,name,role,text,created_at) VALUES(?,?,?,?,?,?,?)").bind(id(),t.id,sender.id,sender.name,sender.role,text,now()).run();
 const ms=await env.DB.prepare("SELECT user_id FROM group_members WHERE group_id=? AND user_id<>?").bind(g.id,sender.id).all();
 for(const m of ms.results)await notify(env,m.user_id,`${sender.name}${sender.blue_verified?" 🔵":""}`,text,"chat",t.id,{groupId:g.id});
 return g;
}
const games=["Free Fire","Mobile Legends","Roblox","PUBG Mobile","eFootball","FC Mobile","Call of Duty Mobile","Valorant","Genshin Impact","Honkai: Star Rail","Wuthering Waves","Clash of Clans","Clash Royale","Minecraft","Steam","TikTok","Arena Breakout","Brawl Stars","League of Legends: Wild Rift","Pokémon Unite","Hay Day","Stumble Guys","Honor of Kings","Garena Undawn","Ragnarok Origin","Dragon Nest","Point Blank","Apex Legends","Fortnite","Rocket League","Dota 2","Counter-Strike 2","Identity V","8 Ball Pool","Growtopia","Sausage Man","Delta Force","Zenless Zone Zero"];
async function route(r,env){
 const u=new URL(r.url),p=u.pathname,m=r.method;if(m==="OPTIONS")return json({ok:true});
 if(p==="/api/health")return json({ok:true,service:"Velora Backend",version:"2.0",database:"Cloudflare D1"});
 if(p==="/api/games"&&m==="GET"){const q=await env.DB.prepare("SELECT id,name FROM games WHERE active=1 ORDER BY name").all();return json({games:q.results.length?q.results:games.map(name=>({id:name.toLowerCase().replace(/\W+/g,"-"),name}))})}
 if(p==="/api/auth/register"&&m==="POST"){const b=await body(r);const email=String(b.email||"").trim().toLowerCase();if(!b.name||!b.password||!/^[^@\s]+@gmail\.com$/i.test(email))return json({error:"Nama, password dan Gmail wajib. Login hanya Gmail."},400);if(await env.DB.prepare("SELECT id FROM users WHERE email=?").bind(email).first())return json({error:"Gmail sudah terdaftar"},409);const uid=id(),ph=await sha(uid+":"+b.password);await env.DB.prepare("INSERT INTO users(id,email,name,password_hash,created_at) VALUES(?,?,?,?,?)").bind(uid,email,String(b.name).trim(),ph,now()).run();return json({ok:true})}
 if(p==="/api/auth/login"&&m==="POST"){const b=await body(r),email=String(b.email||"").trim().toLowerCase(),u=await env.DB.prepare("SELECT * FROM users WHERE email=?").bind(email).first();if(!u)return json({error:"Gmail/password salah"},401);if(await sha(u.id+":"+(b.password||""))!==u.password_hash)return json({error:"Gmail/password salah"},401);const t=id()+id().replaceAll("-",""),exp=now()+90*86400000;await env.DB.prepare("INSERT INTO sessions(token,user_id,expires_at,created_at) VALUES(?,?,?,?)").bind(t,u.id,exp,now()).run();return json({token:t,expiresAt:exp,user:prof(u)})}
 const me=await auth(r,env);if(!me)return json({error:"Unauthorized"},401);
 if(p==="/api/auth/refresh"&&m==="POST"){const t=(r.headers.get("authorization")||"").slice(7),e=now()+90*86400000;await env.DB.prepare("UPDATE sessions SET expires_at=? WHERE token=?").bind(e,t).run();return json({ok:true,expiresAt:e})}
 if(p==="/api/auth/logout"&&m==="POST"){const t=(r.headers.get("authorization")||"").slice(7);await env.DB.prepare("DELETE FROM sessions WHERE token=?").bind(t).run();return json({ok:true})}
 if(p==="/api/me")return json({user:prof(me)});
 if(p==="/api/users"&&m==="GET"){const q=(u.searchParams.get("q")||"").trim().toLowerCase();let sql="SELECT id,name,role,avatar_url,avatar_source,vip,blue_verified FROM users WHERE id<>?";const a=[me.id];if(q){sql+=" AND lower(name) LIKE ?";a.push("%"+q+"%")}sql+=" ORDER BY vip DESC,blue_verified DESC,name LIMIT 50";return json({users:(await env.DB.prepare(sql).bind(...a).all()).results})}
 if(p==="/api/support"&&m==="GET"){const a=await admin(env);if(!a)return json({error:"Admin belum tersedia"},404);return json({user:{id:a.id,name:a.name,role:a.role,avatar_url:a.avatar_url,avatar_source:a.avatar_source,vip:a.vip,blue_verified:a.blue_verified}})}
 if(p==="/api/profile"&&m==="PUT"){const b=await body(r),name=String(b.name||me.name).trim(),av=String(b.avatarUrl||"").trim();await env.DB.prepare("UPDATE users SET name=?,avatar_url=?,avatar_source=? WHERE id=?").bind(name,av,av?"custom":"default",me.id).run();return json({user:prof(await env.DB.prepare("SELECT * FROM users WHERE id=?").bind(me.id).first())})}
 if(p==="/api/push-tokens"&&m==="POST"){const b=await body(r),t=String(b.token||"").trim();if(!t)return json({error:"token wajib"},400);await env.DB.prepare("INSERT INTO push_tokens(id,user_id,token,platform,active,updated_at) VALUES(?,?,?,?,1,?) ON CONFLICT(token) DO UPDATE SET user_id=excluded.user_id,platform=excluded.platform,active=1,updated_at=excluded.updated_at").bind(id(),me.id,t,b.platform||"android",now()).run();return json({ok:true})}
 if(p==="/api/notifications"&&m==="GET"){const n=await env.DB.prepare("SELECT * FROM notifications WHERE user_id=? ORDER BY created_at DESC LIMIT 100").bind(me.id).all();return json({notifications:n.results})}
 if(p==="/api/notifications/read"&&m==="POST"){const b=await body(r);await env.DB.prepare("UPDATE notifications SET read_at=? WHERE id=? AND user_id=?").bind(now(),b.id,me.id).run();return json({ok:true})}
 if(p==="/api/payment-methods"&&m==="GET"){const x=await env.DB.prepare("SELECT id,code,name,kind,account_name,account_number,qr_url,instructions FROM payment_methods WHERE active=1 ORDER BY sort_order").all();return json({methods:x.results})}
 const up=p.match(/^\/api\/uploads\/(avatar|product|verification)\/([A-Za-z0-9._-]+)$/);if(up&&m==="PUT"){const ext=up[2];const key=`${up[1]}/${me.id}/${crypto.randomUUID()}-${ext}`;if(!env.STORAGE)return json({error:"R2 binding STORAGE belum dikonfigurasi"},500);const data=await r.arrayBuffer();if(data.byteLength>8*1024*1024)return json({error:"File maksimal 8MB"},413);await env.STORAGE.put(key,data,{httpMetadata:{contentType:r.headers.get("content-type")||"application/octet-stream"}});return json({ok:true,key,url:`${u.origin}/api/files/${encodeURIComponent(key)}`})}
 const file=p.match(/^\/api\/files\/(.+)$/);if(file&&m==="GET"){if(!env.STORAGE)return json({error:"R2 belum dikonfigurasi"},500);const key=decodeURIComponent(file[1]);const obj=await env.STORAGE.get(key);if(!obj)return new Response("Not found",{status:404});return new Response(obj.body,{headers:{"content-type":obj.httpMetadata?.contentType||"application/octet-stream","cache-control":"public, max-age=31536000"}})}
 if(p==="/api/products"&&m==="GET"){const q=(u.searchParams.get("q")||"").trim();let sql="SELECT p.*,u.name seller_name,u.avatar_url,u.vip,u.blue_verified FROM products p JOIN users u ON u.id=p.seller_id WHERE p.active=1";const a=[];if(q){sql+=" AND (lower(p.title) LIKE ? OR lower(p.game) LIKE ?)";a.push("%"+q.toLowerCase()+"%","%"+q.toLowerCase()+"%")}sql+=" ORDER BY p.created_at DESC LIMIT 100";const x=await env.DB.prepare(sql).bind(...a).all();return json({products:x.results})}
 if(p==="/api/products"&&m==="POST"){if(me.role!=="seller"||!prof(me).sellerActive)return json({error:"Seller aktif diperlukan"},403);const b=await body(r),price=Number(b.price);if(!b.title||!b.game||!price||price<1000)return json({error:"Data produk tidak valid"},400);const pid=id();await env.DB.prepare("INSERT INTO products(id,seller_id,title,game,description,price,login_type,created_at) VALUES(?,?,?,?,?,?,?,?)").bind(pid,me.id,b.title,b.game,b.description||"",price,"gmail",now()).run();return json({id:pid})}
 const prod=p.match(/^\/api\/products\/([^/]+)$/);if(prod&&m==="DELETE"){const x=await env.DB.prepare("SELECT * FROM products WHERE id=? AND seller_id=?").bind(prod[1],me.id).first();if(!x)return json({error:"Forbidden"},403);await env.DB.prepare("UPDATE products SET active=0 WHERE id=?").bind(x.id).run();return json({ok:true})}
 if(p==="/api/seller/plan"&&m==="GET")return json({plans:(await env.DB.prepare("SELECT * FROM seller_plans WHERE active=1").all()).results});
 if(p==="/api/seller/subscribe"&&m==="POST"){const b=await body(r),pl=await env.DB.prepare("SELECT * FROM seller_plans WHERE id=? AND active=1").bind(b.planId).first();if(!pl)return json({error:"Plan tidak ditemukan"},404);if(me.balance<pl.price)return json({error:"Saldo tidak cukup. Untuk sistem manual, admin dapat mengaktifkan seller setelah pembayaran diverifikasi."},400);const s=now(),e=s+pl.duration_days*86400000;await env.DB.prepare("UPDATE users SET role='seller',vip=1,seller_paid_until=?,verified=1 WHERE id=?").bind(e,me.id).run();await env.DB.prepare("INSERT INTO seller_subscriptions(id,seller_id,plan_id,starts_at,expires_at) VALUES(?,?,?,?,?)").bind(id(),me.id,pl.id,s,e).run();return json({ok:true,expiresAt:e})}
 if(p==="/api/transactions"&&m==="GET"){let sql="SELECT t.*,u.name seller_name FROM transactions t JOIN users u ON u.id=t.seller_id WHERE t.buyer_id=? OR t.seller_id=? ORDER BY t.created_at DESC LIMIT 100";return json({transactions:(await env.DB.prepare(sql).bind(me.id,me.id).all()).results})}
 if(p==="/api/transactions"&&m==="POST"){const b=await body(r),pdt=await env.DB.prepare("SELECT p.*,u.name seller_name FROM products p JOIN users u ON u.id=p.seller_id WHERE p.id=? AND p.active=1").bind(b.productId).first();if(!pdt)return json({error:"Produk tidak ditemukan"},404);if(pdt.seller_id===me.id)return json({error:"Tidak bisa membeli produk sendiri"},400);const t=id(),f=fee(pdt.price),total=pdt.price+f;await env.DB.prepare("INSERT INTO transactions(id,buyer_id,seller_id,product_id,title,price,fee,total,created_at) VALUES(?,?,?,?,?,?,?,?,?)").bind(t,me.id,pdt.seller_id,pdt.id,pdt.title,pdt.price,f,total,now()).run();return json({id:t,price:pdt.price,fee:f,total,status:"waiting_payment"})}
 const tx=p.match(/^\/api\/transactions\/([^/]+)$/);if(tx&&m==="GET"){const t=await env.DB.prepare("SELECT * FROM transactions WHERE id=? AND (buyer_id=? OR seller_id=? OR ?='admin')").bind(tx[1],me.id,me.id,me.role).first();if(!t)return json({error:"Forbidden"},403);const pay=await env.DB.prepare("SELECT * FROM payments WHERE transaction_id=?").bind(t.id).first();const g=await env.DB.prepare("SELECT * FROM transaction_groups WHERE transaction_id=?").bind(t.id).first();return json({transaction:t,payment:pay,group:g})}
 if(tx&&m==="POST"){const t=await env.DB.prepare("SELECT * FROM transactions WHERE id=? AND buyer_id=?").bind(tx[1],me.id).first();if(!t)return json({error:"Forbidden"},403);const b=await body(r);const pm=await env.DB.prepare("SELECT * FROM payment_methods WHERE code=? AND active=1").bind(b.method).first();if(!pm)return json({error:"Metode pembayaran tidak tersedia"},400);await env.DB.prepare("INSERT INTO payments(id,transaction_id,method,amount,reference,proof_url,status,created_at) VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(transaction_id) DO UPDATE SET method=excluded.method,amount=excluded.amount,reference=excluded.reference,proof_url=excluded.proof_url,status='pending'").bind(id(),t.id,pm.code,t.total,b.reference||"",b.proofUrl||"","pending",now()).run(); await env.DB.prepare("UPDATE transactions SET status='payment_review' WHERE id=?").bind(t.id).run();const ad0=await admin(env); if(ad0) await notify(env,ad0.id,"Pembayaran baru",`Order ${t.id} menunggu verifikasi.`,"payment",t.id);return json({ok:true,paymentAmount:t.total,method:pm})}
 const proof=p.match(/^\/api\/transactions\/([^/]+)\/proof$/);if(proof&&m==="POST"){const t=await env.DB.prepare("SELECT * FROM transactions WHERE id=? AND buyer_id=?").bind(proof[1],me.id).first();if(!t)return json({error:"Forbidden"},403);const b=await body(r);await env.DB.prepare("UPDATE payments SET proof_url=?,status='submitted' WHERE transaction_id=?").bind(String(b.proofUrl||""),t.id).run();const ad=await admin(env);if(ad)await notify(env,ad.id,"Pembayaran baru perlu diverifikasi",`Buyer mengirim bukti pembayaran untuk ${t.id}.`,"payment",t.id);await notify(env,t.seller_id,"Pembayaran dikirim",`Buyer sudah mengirim bukti pembayaran ${t.id}.`,"payment",t.id);return json({ok:true})}
 if(p==="/api/transactions/quote"&&m==="POST"){const b=await body(r),x=await env.DB.prepare("SELECT price FROM products WHERE id=? AND active=1").bind(b.productId).first();if(!x)return json({error:"Produk tidak ditemukan"},404);return json({price:x.price,fee:fee(x.price),total:x.price+fee(x.price)})}
 const gr=p.match(/^\/api\/transactions\/([^/]+)\/group$/);if(gr&&m==="GET"){const t=await env.DB.prepare("SELECT * FROM transactions WHERE id=? AND (buyer_id=? OR seller_id=? OR ?='admin')").bind(gr[1],me.id,me.id,me.role).first();if(!t)return json({error:"Forbidden"},403);const g=await env.DB.prepare("SELECT * FROM transaction_groups WHERE transaction_id=?").bind(t.id).first();if(!g)return json({error:"Group belum dibuat"},404);const members=await env.DB.prepare("SELECT gm.role,u.id,u.name,u.avatar_url,u.avatar_source,u.vip,u.blue_verified FROM group_members gm JOIN users u ON u.id=gm.user_id WHERE gm.group_id=?").bind(g.id).all();return json({group:g,members:members.results})}
 const tm=p.match(/^\/api\/transactions\/([^/]+)\/messages$/);if(tm&&m==="GET"){const t=await env.DB.prepare("SELECT * FROM transactions WHERE id=? AND (buyer_id=? OR seller_id=? OR ?='admin')").bind(tm[1],me.id,me.id,me.role).first();if(!t)return json({error:"Forbidden"},403);return json({messages:(await env.DB.prepare("SELECT m.*,u.avatar_url,u.avatar_source,u.vip,u.blue_verified FROM messages m JOIN users u ON u.id=m.uid WHERE m.room_id=? ORDER BY m.created_at ASC").bind(t.id).all()).results})}
 if(tm&&m==="POST"){const t=await env.DB.prepare("SELECT * FROM transactions WHERE id=? AND (buyer_id=? OR seller_id=? OR ?='admin')").bind(tm[1],me.id,me.id,me.role).first();if(!t)return json({error:"Forbidden"},403);const b=await body(r),text=String(b.text||"").trim();if(!text)return json({error:"Pesan kosong"},400);const g=await sendGroup(env,t,me,text);return json({ok:true,groupId:g.id})}
 const cp=p.match(/^\/api\/chats\/([^/]+)\/messages$/);
 if(p==="/api/chats"&&m==="POST"){const b=await body(r),target=String(b.userId||"");if(!target||target===me.id)return json({error:"userId tidak valid"},400);const o=await env.DB.prepare("SELECT id FROM users WHERE id=?").bind(target).first();if(!o)return json({error:"User tidak ditemukan"},404);const a=me.id<target?me.id:target,bb=me.id<target?target:me.id;let c=await env.DB.prepare("SELECT * FROM chats WHERE user_a=? AND user_b=?").bind(a,bb).first();if(!c){const cid=id();await env.DB.prepare("INSERT INTO chats(id,kind,user_a,user_b,created_at,updated_at) VALUES(?,?,?,?,?,?)").bind(cid,"direct",a,bb,now(),now()).run();c=await env.DB.prepare("SELECT * FROM chats WHERE id=?").bind(cid).first()}return json({chat:c})}
 if(p==="/api/chats"&&m==="GET"){const q=await env.DB.prepare("SELECT c.id,c.updated_at,CASE WHEN c.user_a=? THEN c.user_b ELSE c.user_a END other_id,u.name other_name,u.avatar_url,u.avatar_source,u.role,u.vip,u.blue_verified,(SELECT text FROM chat_messages cm WHERE cm.chat_id=c.id ORDER BY cm.created_at DESC LIMIT 1) last_text FROM chats c JOIN users u ON u.id=CASE WHEN c.user_a=? THEN c.user_b ELSE c.user_a END WHERE c.user_a=? OR c.user_b=? ORDER BY c.updated_at DESC").bind(me.id,me.id,me.id,me.id).all();return json({chats:q.results})}
 if(cp&&m==="GET"){const c=await env.DB.prepare("SELECT * FROM chats WHERE id=? AND (user_a=? OR user_b=?)").bind(cp[1],me.id,me.id).first();if(!c)return json({error:"Forbidden"},403);return json({messages:(await env.DB.prepare("SELECT cm.*,u.name,u.role,u.avatar_url,u.avatar_source,u.vip,u.blue_verified FROM chat_messages cm JOIN users u ON u.id=cm.sender_id WHERE cm.chat_id=? ORDER BY cm.created_at ASC").bind(cp[1]).all()).results})}
 if(cp&&m==="POST"){const c=await env.DB.prepare("SELECT * FROM chats WHERE id=? AND (user_a=? OR user_b=?)").bind(cp[1],me.id,me.id).first();if(!c)return json({error:"Forbidden"},403);const b=await body(r),text=String(b.text||"").trim();if(!text)return json({error:"Pesan kosong"},400);const mid=id();await env.DB.prepare("INSERT INTO chat_messages(id,chat_id,sender_id,text,created_at) VALUES(?,?,?,?,?)").bind(mid,c.id,me.id,text,now()).run();await env.DB.prepare("UPDATE chats SET updated_at=? WHERE id=?").bind(now(),c.id).run();const other=c.user_a===me.id?c.user_b:c.user_a;await notify(env,other,`${me.name}${me.blue_verified?" 🔵":""}`,text,"chat",c.id);const ad=await admin(env);if(ad&&ad.id!==me.id&&ad.id!==other)await notify(env,ad.id,`${me.name} chat`,text,"chat",c.id);return json({id:mid})}
 if(p==="/api/delivery"&&m==="POST"){const b=await body(r),t=await env.DB.prepare("SELECT * FROM transactions WHERE id=? AND seller_id=?").bind(b.transactionId,me.id).first();if(!t)return json({error:"Seller only"},403);if(t.status!=="payment_verified")return json({error:"Admin belum memverifikasi pembayaran"},400);if(!/^[^@\s]+@gmail\.com$/i.test(b.email||"")||!b.password)return json({error:"Delivery wajib Gmail + password"},400);const c=await encDelivery(JSON.stringify({email:b.email,password:b.password}),env.DELIVERY_SECRET);await env.DB.prepare("INSERT OR REPLACE INTO deliveries(transaction_id,email,password_cipher,created_at) VALUES(?,?,?,?)").bind(t.id,b.email,c,now()).run();await env.DB.prepare("UPDATE transactions SET status='delivered' WHERE id=?").bind(t.id).run();await sendGroup(env,t,me,"Seller telah mengirim akun melalui delivery terenkripsi.");await notify(env,t.buyer_id,"Seller telah mengirim akun","Data akun sudah tersedia di pesanan.","delivery",t.id);return json({ok:true})}
 const del=p.match(/^\/api\/transactions\/([^/]+)\/delivery$/);if(del&&m==="GET"){const t=await env.DB.prepare("SELECT * FROM transactions WHERE id=? AND buyer_id=?").bind(del[1],me.id).first();if(!t)return json({error:"Forbidden"},403);const d=await env.DB.prepare("SELECT * FROM deliveries WHERE transaction_id=?").bind(t.id).first();if(!d)return json({error:"Belum ada delivery"},404);try{return json({delivery:JSON.parse(await decDelivery(d.password_cipher,env.DELIVERY_SECRET))})}catch{return json({error:"Delivery secret tidak cocok"},500)}}
 if(p==="/api/transactions/complete"&&m==="POST"){const b=await body(r),t=await env.DB.prepare("SELECT * FROM transactions WHERE id=? AND buyer_id=?").bind(b.transactionId,me.id).first();if(!t||t.status!=="delivered")return json({error:"Transaksi belum siap diselesaikan"},400);await env.DB.prepare("UPDATE transactions SET status='completed',completed_at=? WHERE id=?").bind(now(),t.id).run();await env.DB.prepare("UPDATE users SET balance=balance+? WHERE id=?").bind(t.price,t.seller_id).run();await notify(env,t.seller_id,"Pesanan selesai",`Buyer menyelesaikan ${t.id}.`,"completed",t.id);return json({ok:true})}
 if(p==="/api/withdrawals"&&m==="POST"){if(me.role!=="seller")return json({error:"Seller only"},403);const b=await body(r),a=Number(b.amount);if(a<10000||a>me.balance)return json({error:"Nominal tidak valid"},400);const w=id();await env.DB.prepare("INSERT INTO withdrawals(id,seller_id,amount,method,destination,created_at) VALUES(?,?,?,?,?,?)").bind(w,me.id,a,b.method,b.destination,now()).run();await env.DB.prepare("UPDATE users SET balance=balance-? WHERE id=?").bind(a,me.id).run();const ad=await admin(env);if(ad)await notify(env,ad.id,"Withdraw baru",`Seller ${me.name} meminta ${a}.`,"withdrawal",w);return json({id:w,status:"requested"})}
 if(p==="/api/admin/stats"&&m==="GET"&&me.role==="admin"){const [a,b,c,d]=await Promise.all(["SELECT COUNT(*) n FROM users","SELECT COUNT(*) n FROM products WHERE active=1","SELECT COUNT(*) n FROM transactions","SELECT COUNT(*) n FROM withdrawals WHERE status='requested'"].map(q=>env.DB.prepare(q).first()));return json({users:a.n,products:b.n,transactions:c.n,pendingWithdrawals:d.n})}
 if(p==="/api/admin/bootstrap"&&m==="POST"){const b=await body(r);if(!env.ADMIN_BOOTSTRAP_SECRET||b.secret!==env.ADMIN_BOOTSTRAP_SECRET)return json({error:"Secret salah"},403);const target=await env.DB.prepare("SELECT id FROM users WHERE id=?").bind(b.userId||me.id).first();if(!target)return json({error:"User tidak ditemukan"},404);await env.DB.prepare("UPDATE users SET role='admin',vip=1,blue_verified=1,verified=1 WHERE id=?").bind(target.id).run();return json({ok:true})}
 if(p==="/api/admin/verify-payment"&&m==="POST"&&me.role==="admin"){const b=await body(r),t=await env.DB.prepare("SELECT * FROM transactions WHERE id=?").bind(b.transactionId).first();if(!t)return json({error:"Transaksi tidak ditemukan"},404);const pay=await env.DB.prepare("SELECT * FROM payments WHERE transaction_id=?").bind(t.id).first();if(!pay)return json({error:"Pembayaran belum dibuat"},400);await env.DB.prepare("UPDATE payments SET status='verified',verified_at=? WHERE transaction_id=?").bind(now(),t.id).run();await env.DB.prepare("UPDATE transactions SET status='payment_verified',paid_at=? WHERE id=?").bind(now(),t.id).run();const g=await group(env,t);await sendGroup(env,t,me,"Dana masuk ✅\nSilahkan kirim Gmail dan password melalui delivery.");await notify(env,t.seller_id,"Dana masuk ✅","Pembayaran sudah diverifikasi. Silakan kirim data akun.","payment_verified",t.id,{groupId:g.id});await notify(env,t.buyer_id,"Pembayaran diverifikasi","Pesanan sedang diproses.","payment_verified",t.id,{groupId:g.id});return json({ok:true,groupId:g.id})}
 if(p==="/api/admin/verify-seller"&&m==="POST"&&me.role==="admin"){const b=await body(r);await env.DB.prepare("UPDATE users SET role='seller',verified=1,vip=1,seller_trial_until=? WHERE id=?").bind(now()+15*86400000,b.userId).run();return json({ok:true})}
 if(p==="/api/admin/payment-methods"&&m==="PUT"&&me.role==="admin"){const b=await body(r);if(!b.code||!b.name)return json({error:"code/name wajib"},400);await env.DB.prepare("UPDATE payment_methods SET name=?,account_name=?,account_number=?,qr_url=?,instructions=?,active=?,sort_order=?,updated_at=? WHERE code=?").bind(b.name,b.accountName||"",b.accountNumber||"",b.qrUrl||"",b.instructions||"",b.active===false?0:1,Number(b.sortOrder||0),now(),b.code).run();return json({ok:true})}
 if(p==="/api/admin/users"&&m==="GET"&&me.role==="admin"){return json({users:(await env.DB.prepare("SELECT id,email,name,role,verified,vip,blue_verified,balance,created_at FROM users ORDER BY created_at DESC LIMIT 500").all()).results})}
 if(p==="/api/admin/withdrawals"&&m==="GET"&&me.role==="admin"){return json({withdrawals:(await env.DB.prepare("SELECT * FROM withdrawals ORDER BY created_at DESC LIMIT 200").all()).results})}
 return json({error:"Not found"},404)
}
export default {async fetch(r,e){try{return await route(r,e)}catch(x){return json({error:"Server error",detail:String(x?.message||x)},500)}}};
